--new TYPE called grocery
------ENUM- Main, Snack, Lunch, Breakfast

DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

--new table called shopping_list
----with 6 columns 
--------none should allow nulls
-------------primary key id
-------------a name column
-------------price should not be string, support 2 decimals
-------------date_added, default now()
-------------checked column, BOOLEAN, default of false
-------------category column, grocery type



CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
)



